apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tester-deployment
  namespace: api-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tester
  template:
    metadata:
      labels:
        app: api-tester
    spec:
      containers:
        - name: api-tester
          image: api-tester:latest
          ports:
            - containerPort: 3000  # Frontend port
            - containerPort: 5000  # Backend port
          env:
            - name: MONGO_URI
              value: "mongodb+srv://nikossmokas:dU1nwBSHJSUui8Ck@automatedtestscluster.zfklqfu.mongodb.net/"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
