apiVersion: v1
kind: Service
metadata:
  name: fullstack-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: frontend
    - port: 5000
      targetPort: 5000
      name: backend
  selector:
    app: fullstack
